# -*- coding: utf-8 -*-
"""Qdrant vector DB .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ifPjM73TIKtjxSoecNbB-Tsk5IMUJmae
"""

QDRANT_API_KEY = "####"
QDRANT_URL = "##########"
client = qdrant_client.QdrantClient(url=QDRANT_URL, api_key=QDRANT_API_KEY)

COLLECTION_NAME = "medical_documents"
# COLLECTION_NAME = "medical_documents2"

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.5",
    "Connection": "keep-alive",
    "Upgrade-Insecure-Requests": "1"
}

def create_collection():
    """Create a new collection in Qdrant (Handles deprecated method)."""
    client.delete_collection(collection_name=COLLECTION_NAME) # Ensure fresh start
    client.create_collection(
        collection_name=COLLECTION_NAME,
        vectors_config=VectorParams(size=768, distance=Distance.COSINE) # BioBERT output size is 768
    )
    print(f"✅ Collection '{COLLECTION_NAME}' created.")